export type SpeciesKey =
  | "dogs"
  | "cats"
  | "rabbits"
  | "turtle"
  | "hamster"
  | "parrots"
  | "snakes"
  | "lizards"
  | "others";

export type BreedOption = { en: string; zh: string };
export type SpeciesOption = { key: SpeciesKey; en: string; zh: string };

const dog = (en: string, zh: string): BreedOption => ({ en, zh });
const cat = (en: string, zh: string): BreedOption => ({ en, zh });

export const SPECIES_OPTIONS: SpeciesOption[] = [
  { key: "dogs", en: "Dogs", zh: "狗" },
  { key: "cats", en: "Cats", zh: "貓" },
  { key: "rabbits", en: "Rabbits", zh: "兔" },
  { key: "turtle", en: "Turtle", zh: "龜" },
  { key: "hamster", en: "Hamster", zh: "倉鼠" },
  { key: "parrots", en: "Parrots / Birds", zh: "鸚鵡／鳥類" },
  { key: "snakes", en: "Snakes", zh: "蛇" },
  { key: "lizards", en: "Lizards", zh: "蜥蜴" },
  { key: "others", en: "Others", zh: "其他" },
];

export const PET_BREEDS_BY_SPECIES: Record<Exclude<SpeciesKey, "others">, BreedOption[]> = {
  dogs: [
    dog("Mixed breed", "米克斯"),
    dog("Shiba Inu", "柴犬"),
    dog("Miniature Schnauzer", "迷你雪納瑞"),
    dog("Standard Schnauzer", "標準雪納瑞"),
    dog("Giant Schnauzer", "巨型雪納瑞"),
    dog("Poodle (Toy)", "玩具貴賓"),
    dog("Poodle (Miniature)", "迷你貴賓"),
    dog("Poodle (Standard)", "標準貴賓"),
    dog("Poodle mix", "貴賓混種犬"),
    dog("Golden Retriever", "黃金獵犬"),
    dog("Labrador Retriever", "拉布拉多"),
    dog("Siberian Husky", "哈士奇"),
    dog("Alaskan Malamute", "阿拉斯加雪橇犬"),
    dog("Welsh Corgi (Pembroke)", "威爾斯柯基（彭布羅克）"),
    dog("Welsh Corgi (Cardigan)", "威爾斯柯基（卡迪根）"),
    dog("French Bulldog", "法國鬥牛犬"),
    dog("English Bulldog", "英國鬥牛犬"),
    dog("American Bulldog", "美國鬥牛犬"),
    dog("Pomeranian", "博美"),
    dog("Chihuahua", "吉娃娃"),
    dog("Yorkshire Terrier", "約克夏"),
    dog("Dachshund", "臘腸犬"),
    dog("Bichon Frise", "比熊犬"),
    dog("Border Collie", "邊境牧羊犬"),
    dog("German Shepherd", "德國牧羊犬"),
    dog("Akita Inu", "秋田犬"),
    dog("Chow Chow", "鬆獅犬"),
    dog("Shih Tzu", "西施犬"),
    dog("Maltese", "瑪爾濟斯"),
    dog("Cavalier King Charles Spaniel", "騎士查理王獵犬"),
    dog("Cocker Spaniel", "可卡獵犬"),
    dog("Beagle", "米格魯"),
    dog("Jack Russell Terrier", "傑克羅素㹴"),
    dog("West Highland White Terrier", "西高地白㹴"),
    dog("Scottish Terrier", "蘇格蘭㹴"),
    dog("Boston Terrier", "波士頓㹴"),
    dog("Australian Shepherd", "澳洲牧羊犬"),
    dog("Shetland Sheepdog", "喜樂蒂牧羊犬"),
    dog("Doberman Pinscher", "杜賓犬"),
    dog("Rottweiler", "羅威納"),
    dog("Boxer", "拳師犬"),
    dog("Great Dane", "大丹犬"),
    dog("Saint Bernard", "聖伯納"),
    dog("Bernese Mountain Dog", "伯恩山犬"),
    dog("Samoyed", "薩摩耶"),
    dog("Japanese Spitz", "日本銀狐"),
    dog("Pug", "巴哥犬"),
    dog("Chinese Crested", "中國冠毛犬"),
    dog("Italian Greyhound", "義大利靈緹"),
    dog("Whippet", "惠比特"),
    dog("Greyhound", "格雷伊獵犬"),
    dog("Weimaraner", "威瑪獵犬"),
    dog("Vizsla", "維茲拉獵犬"),
    dog("Pointer", "指示獵犬"),
    dog("Dalmatian", "大麥町"),
    dog("Shar Pei", "沙皮狗"),
    dog("Tibetan Mastiff", "藏獒"),
    dog("Akita (American)", "美系秋田"),
    dog("Belgian Malinois", "比利時馬利諾斯"),
    dog("Dutch Shepherd", "荷蘭牧羊犬"),
    dog("Rough Collie", "蘇格蘭牧羊犬"),
    dog("Old English Sheepdog", "古代英國牧羊犬"),
    dog("Mastiff", "獒犬"),
    dog("Bull Terrier", "牛頭㹴"),
    dog("Staffordshire Bull Terrier", "斯塔福郡鬥牛㹴"),
    dog("American Pit Bull Terrier", "比特犬"),
    dog("Basenji", "巴辛吉"),
    dog("Afghan Hound", "阿富汗獵犬"),
    dog("Irish Setter", "愛爾蘭雪達犬"),
    dog("English Setter", "英國雪達犬"),
    dog("Cane Corso", "卡斯羅"),
    dog("Dogo Argentino", "阿根廷杜告犬"),
    dog("Other (enter below)", "其他（請於下方填寫）"),
  ],
  cats: [
    cat("Mixed / Domestic", "米克斯／家貓"),
    cat("British Shorthair", "英國短毛貓"),
    cat("American Shorthair", "美國短毛貓"),
    cat("Persian", "波斯貓"),
    cat("Exotic Shorthair", "異國短毛貓"),
    cat("Ragdoll", "布偶貓"),
    cat("Maine Coon", "緬因貓"),
    cat("Scottish Fold", "蘇格蘭摺耳貓"),
    cat("Siamese", "暹羅貓"),
    cat("Bengal", "孟加拉豹貓"),
    cat("Sphynx", "斯芬克斯（無毛貓）"),
    cat("Russian Blue", "俄羅斯藍貓"),
    cat("Norwegian Forest", "挪威森林貓"),
    cat("Siberian", "西伯利亞貓"),
    cat("Turkish Angora", "土耳其安哥拉貓"),
    cat("Turkish Van", "土耳其梵貓"),
    cat("Abyssinian", "阿比西尼亞貓"),
    cat("Birman", "伯曼貓"),
    cat("Himalayan", "喜馬拉雅貓"),
    cat("Manx", "曼島貓"),
    cat("Munchkin", "曼赤肯（短腿貓）"),
    cat("Devon Rex", "德文捲毛貓"),
    cat("Cornish Rex", "康沃爾捲毛貓"),
    cat("Oriental Shorthair", "東方短毛貓"),
    cat("Burmese", "緬甸貓"),
    cat("Singapura", "新加坡貓"),
    cat("Somali", "索馬利貓"),
    cat("Chartreux", "夏特勒貓"),
    cat("American Curl", "美國捲耳貓"),
    cat("Japanese Bobtail", "日本短尾貓"),
    cat("Other (enter below)", "其他（請於下方填寫）"),
  ],
  rabbits: [
    { en: "Mixed", zh: "米克斯" },
    { en: "Holland Lop", zh: "荷蘭垂耳兔" },
    { en: "Mini Lop", zh: "迷你垂耳兔" },
    { en: "Netherland Dwarf", zh: "荷蘭侏儒兔" },
    { en: "Lionhead", zh: "獅子頭兔" },
    { en: "Angora", zh: "安哥拉兔" },
    { en: "Rex", zh: "雷克斯兔" },
    { en: "Mini Rex", zh: "迷你雷克斯" },
    { en: "English Spot", zh: "英國斑點兔" },
    { en: "Californian", zh: "加利福尼亞兔" },
    { en: "Flemish Giant", zh: "比利時巨型兔" },
    { en: "New Zealand", zh: "紐西蘭兔" },
    { en: "Dutch", zh: "道奇兔" },
    { en: "Polish", zh: "波蘭兔" },
    { en: "Himalayan (rabbit)", zh: "喜馬拉雅兔" },
    { en: "Other (enter below)", zh: "其他（請於下方填寫）" },
  ],
  turtle: [
    { en: "Red-eared slider", zh: "巴西龜（紅耳龜）" },
    { en: "Yellow-bellied slider", zh: "黃肚龜" },
    { en: "Map turtle", zh: "地圖龜" },
    { en: "Painted turtle", zh: "錦龜" },
    { en: "Musk turtle", zh: "麝香龜" },
    { en: "Box turtle", zh: "箱龜" },
    { en: "Russian tortoise", zh: "俄羅斯陸龜" },
    { en: "Sulcata tortoise", zh: "蘇卡達象龜" },
    { en: "Leopard tortoise", zh: "豹龜" },
    { en: "Greek tortoise", zh: "希臘陸龜" },
    { en: "Hermann’s tortoise", zh: "赫曼陸龜" },
    { en: "Snapping turtle", zh: "鱷龜" },
    { en: "Softshell turtle", zh: "鼈／軟殼龜" },
    { en: "Sea turtle (rescue)", zh: "海龜（救傷／保育）" },
    { en: "Unknown / Mixed", zh: "未知／混種" },
    { en: "Other (enter below)", zh: "其他（請於下方填寫）" },
  ],
  hamster: [
    { en: "Syrian (Golden)", zh: "黃金鼠（敘利亞倉鼠）" },
    { en: "Dwarf Campbell", zh: "一線（加卡利亞）" },
    { en: "Dwarf Winter White", zh: "冬白倉鼠" },
    { en: "Roborovski", zh: "老公公／老婆婆" },
    { en: "Chinese hamster", zh: "中國倉鼠" },
    { en: "Hybrid / Unknown dwarf", zh: "侏儒混種／未知" },
    { en: "Other (enter below)", zh: "其他（請於下方填寫）" },
  ],
  parrots: [
    { en: "Budgerigar (Budgie)", zh: "虎皮鸚鵡" },
    { en: "Cockatiel", zh: "雞尾鸚鵡（玄鳳）" },
    { en: "Lovebird", zh: "愛情鳥" },
    { en: "Canary", zh: "金絲雀" },
    { en: "Finch", zh: "雀科" },
    { en: "Cockatoo", zh: "鳳頭鸚鵡" },
    { en: "Macaw", zh: "金剛鸚鵡" },
    { en: "African Grey", zh: "非洲灰鸚鵡" },
    { en: "Amazon parrot", zh: "亞馬遜鸚鵡" },
    { en: "Eclectus", zh: "折衷鸚鵡" },
    { en: "Conure", zh: "錐尾鸚鵡" },
    { en: "Quaker parakeet", zh: "和尚鸚鵡" },
    { en: "Ring-necked parakeet", zh: "月輪鸚鵡" },
    { en: "Rosella", zh: "玫瑰鸚鵡" },
    { en: "Lorikeet / Lory", zh: "吸蜜鸚鵡" },
    { en: "Other (enter below)", zh: "其他（請於下方填寫）" },
  ],
  snakes: [
    { en: "Ball python", zh: "球蟒" },
    { en: "Corn snake", zh: "玉米蛇" },
    { en: "King snake", zh: "王蛇" },
    { en: "Milk snake", zh: "奶蛇" },
    { en: "Boa constrictor", zh: "紅尾蚺" },
    { en: "Rainbow boa", zh: "彩虹蚺" },
    { en: "Hognose snake", zh: "豬鼻蛇" },
    { en: "Garter snake", zh: "束帶蛇" },
    { en: "Rat snake", zh: "錦蛇" },
    { en: "Children’s python", zh: "兒童蟒" },
    { en: "Carpet python", zh: "地毯蟒" },
    { en: "Green tree python", zh: "綠樹蟒" },
    { en: "Other colubrid", zh: "其他游蛇科" },
    { en: "Other (enter below)", zh: "其他（請於下方填寫）" },
  ],
  lizards: [
    { en: "Bearded dragon", zh: "鬆獅蜥（鬃獅蜥）" },
    { en: "Leopard gecko", zh: "豹紋守宮" },
    { en: "Crested gecko", zh: "睫角守宮" },
    { en: "Tokay gecko", zh: "大守宮" },
    { en: "Fat-tailed gecko", zh: "肥尾守宮" },
    { en: "Green iguana", zh: "綠鬣蜥" },
    { en: "Blue tongue skink", zh: "藍舌蜥" },
    { en: "Uromastyx", zh: "刺尾蜥" },
    { en: "Tegu", zh: "泰加蜥" },
    { en: "Monitor lizard", zh: "巨蜥" },
    { en: "Anole", zh: "安樂蜥" },
    { en: "Chinese water dragon", zh: "長鬣蜥（水龍）" },
    { en: "Other (enter below)", zh: "其他（請於下方填寫）" },
  ],
};

export function getBreedsForSpecies(species: SpeciesKey): BreedOption[] | null {
  if (!species || species === "others") return null;
  return PET_BREEDS_BY_SPECIES[species] || null;
}

export function labelBreed(item: BreedOption, isZh: boolean) {
  return isZh ? item.zh : item.en;
}
