import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/seo";

const SENSITIVE_DISALLOW = [
  "/api/",
  "/admin/",
  "/admin-forms-secret",
  "/auth/",
  "/signup-login",
  "/register",
  "/forgot-password",
  "/verification-code",
  "/delete-account",
  "/mailgoogleform",
  "/account",
  "/account/",
  "/wishlist",
  "/compare",
  "/check/",
  "/activate/",
  "/pet/",
  "/vendor-application/thank-you",
  "/test-booking",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: SENSITIVE_DISALLOW,
      },
      { userAgent: "OAI-SearchBot", allow: "/" },
      { userAgent: "ChatGPT-User", allow: "/" },
      { userAgent: "PerplexityBot", allow: "/" },
      { userAgent: "Perplexity-User", allow: "/" },
      { userAgent: "Claude-SearchBot", allow: "/" },
      { userAgent: "Claude-User", allow: "/" },
      { userAgent: "Twitterbot", allow: "/" },
      { userAgent: "facebookexternalhit", allow: "/" },
      { userAgent: "LinkedInBot", allow: "/" },
      { userAgent: "WhatsApp", allow: "/" },
      { userAgent: "GPTBot", disallow: "/" },
      { userAgent: "CCBot", disallow: "/" },
      { userAgent: "anthropic-ai", disallow: "/" },
      { userAgent: "ClaudeBot", disallow: "/" },
      { userAgent: "Claude-Web", disallow: "/" },
      { userAgent: "Google-Extended", disallow: "/" },
      { userAgent: "Bytespider", disallow: "/" },
      { userAgent: "Amazonbot", disallow: "/" },
      { userAgent: "Applebot-Extended", disallow: "/" },
      { userAgent: "cohere-ai", disallow: "/" },
      { userAgent: "Meta-ExternalAgent", disallow: "/" },
      { userAgent: "Diffbot", disallow: "/" },
    ],
    sitemap: [
      `${SITE_URL}/sitemap-index.xml`,
      `${SITE_URL}/sitemap.xml`,
      `${SITE_URL}/price-sitemap.xml`,
      `${SITE_URL}/restaurant-sitemap.xml`,
      `${SITE_URL}/clinic-sitemap.xml`,
      `${SITE_URL}/salon-sitemap.xml`,
      `${SITE_URL}/lodging-sitemap.xml`,
      `${SITE_URL}/mall-sitemap.xml`,
      `${SITE_URL}/home-visit-sitemap.xml`,
      `${SITE_URL}/forum-sitemap.xml`,
      `${SITE_URL}/event-sitemap.xml`,
    ],
    host: SITE_URL,
  };
}
